 version: "3"
 services:
   db:
     image: mysql:8.0.26
     restart: always
     command:
        - --lower_case_table_names=1
        - --character-set-server=utf8mb4
        - --collection-server=utf8mb4_unicode_ci
     container_name: mysql
     ports:
       - "33068:33068"
     environment:
       - MYSQL_DATABASE=mydb
       - MYSQL_ROOT_PASSWORD=0805
       - TZ=Aaia/Seoul
     volumes:
       - C:\intelliJEdu\mysql